Name = "51DNS"
Description = ''''''
URL = "https://www.51dns.com"
Code = "dns51"
Since = "v5.0.0"

Example = '''
DNS51_API_KEY="xxx" \
DNS51_API_SECRET="yyy" \
lego run --dns dns51 -d '*.example.com' -d example.com
'''

[Configuration]
  [Configuration.Credentials]
    DNS51_API_KEY = "API key"
    DNS51_API_SECRET = "API secret"
  [Configuration.Additional]
    DNS51_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    DNS51_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    DNS51_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    DNS51_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://www.51dns.com/document/api/4/81.html"
