// Code generated by 'internal/releaser'; DO NOT EDIT.

package main

const defaultVersion = "v5.3.0+dev-detach"

var version = ""

func getVersion() string {
	if version == "" {
		return defaultVersion
	}

	return version
}
