Name = "Hosting.nl"
Description = ''''''
URL = "https://hosting.nl"
Code = "hostingnl"
Since = "v4.16.0"

Example = '''
HOSTINGNL_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --email myemail@example.com --dns hostingnl --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    HOSTINGNL_API_KEY = "The API key"
  [Configuration.Additional]
    HOSTINGNL_POLLING_INTERVAL = "Time between DNS propagation check"
    HOSTINGNL_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    HOSTINGNL_TTL = "The TTL of the TXT record used for the DNS challenge"
    HOSTINGNL_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://api.hosting.nl/api/documentation"
