Name = "Enum"
Description = ''''''
URL = "https://enum.co"
Code = "enum"
Since = "v5.6.0"

Example = '''
ENUM_API_TOKEN="xxx" \
lego run --dns enum -d '*.example.com' -d example.com

# or

ENUM_CREDENTIALS="example.com:xxx,example.org:yyy" \
lego run --dns enum -d '*.example.com' -d example.com
'''

[Configuration]
  [Configuration.Credentials]
    ENUM_API_TOKEN = "API token."
    ENUM_CREDENTIALS = "Overides API token. Mapping of zone name and API token."
[Configuration.Additional]
    ENUM_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    ENUM_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    ENUM_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    ENUM_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://docs.enum.co/api/"
  GoClient = "https://github.com/enumco/client-go"
