name: 🐞 Bug Report
description: Create a report to help us improve.
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I'm using a binary release or the library within the two latest releases.
          required: true
        - label: Yes, I've searched for similar issues on GitHub and didn't find any.
          required: true

  - type: markdown
    attributes:
      value: |
        #### Do you want your request to be released in a specific timeframe?

        If it is possible to implement it, your request should be released (after implementation, review, and merge):

        - In 1 week (7 days) maximum. Requires [High priority tier](https://github.com/sponsors/ldez/sponsorships?tier_id=605810).
        - In 2 days maximum. Requires [Critical priority tier](https://github.com/sponsors/ldez/sponsorships?tier_id=605811).

  - type: dropdown
    id: type
    attributes:
      label: How do you use lego?
      # This is required because of a bug in Issue Forms:
      # The first option is always selected unless you are using the "multiple" attribute.
      multiple: true
      options:
        - Library
        - Binary
        - Docker image
        - go install
        - Through 1Panel
        - Through Bitnami
        - Through Caddy
        - Through Certimate
        - Through Dokku plugin
        - Through Home Assistant plugin
        - Through Terraform ACME provider
        - Through Traefik
        - Through Zoraxy
        - Other (please explain)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Effective version of lego
      description: "`latest` or `dev` are NOT effective versions."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      value: |-
        <details>

        ```console
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
      placeholder: Description.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: What did you see instead?
      placeholder: Description.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1. ...
        2. ...
        3. ...
        ...
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go environment (if applicable)
      value: |-
        <details>

        ```console
        $ go version && go env
        # paste output here
        ```

        </details>
    validations:
      required: false

  - type: dropdown
    id: usage
    attributes:
      label: In which context are you using lego?
      # This is required because of a bug in Issue Forms:
      # The first option is always selected unless you are using the "multiple" attribute.
      multiple: true
      options:
        - Personal use
        - Professional use
        - Personal and professional use
        - Other (please explain)
    validations:
      required: true
  - type: checkboxes
    id: value-affirmation
    attributes:
      label: 🌱 Supporting the Maintainer
      options:
        - label: "Yes, I find this project useful, and it has saved me time in my workflow/business."
          required: false
        - label: "Yes, I have [starred](https://github.com/go-acme/lego) this repository to help others find it."
          required: false
        - label: "Yes, I have [sponsored](https://donate.ldez.dev) this project to keep the project stable and maintained."
          required: false

  - type: markdown
    attributes:
      value: |
        Your support ensures this tool remains a reliable part of your toolkit for years to come.

        [Support Project Longevity →](https://donate.ldez.dev)

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all the information above (version, usage, etc.).
          required: true
