name: 💡 Feature request
description: Suggest an idea for this project.
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I've searched for similar issues on GitHub and didn't find any.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      placeholder: Description.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Effective version of lego
      description: "`latest` or `dev` are NOT effective versions."
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: How do you use lego?
      # This is required because of a bug in Issue Forms:
      # The first option is always selected unless you are using the "multiple" attribute.
      multiple: true
      options:
        - Library
        - Binary
        - Docker image
        - go install
        - Through 1Panel
        - Through Bitnami
        - Through Caddy
        - Through Certimate
        - Through Dokku plugin
        - Through Home Assistant plugin
        - Through Terraform ACME provider
        - Through Traefik
        - Through Zoraxy
        - Other (please explain)
    validations:
      required: true

  - type: dropdown
    id: usage
    attributes:
      label: In which context are you using lego?
      # This is required because of a bug in Issue Forms:
      # The first option is always selected unless you are using the "multiple" attribute.
      multiple: true
      options:
        - Personal use
        - Professional use
        - Personal and professional use
        - Other (please explain)
    validations:
      required: true

  - type: checkboxes
    id: value-affirmation
    attributes:
      label: 🌱 Supporting the Maintainer
      options:
        - label: "Yes, I find this project useful, and it has saved me time in my workflow/business."
          required: false
        - label: "Yes, I have [starred](https://github.com/go-acme/lego) this repository to help others find it."
          required: false
        - label: "Yes, I have [sponsored](https://donate.ldez.dev) this project to keep the project stable and maintained."
          required: false

  - type: markdown
    attributes:
      value: |
        Your support ensures this tool remains a reliable part of your toolkit for years to come.

        [Support Project Longevity →](https://donate.ldez.dev)

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all the information above (version, usage, etc.).
          required: true
