Name = "Excedo"
Description = ''''''
URL = "https://excedo.se/"
Code = "excedo"
Since = "v4.33.0"

Example = '''
EXCEDO_API_KEY=your-api-key \
EXCEDO_API_URL=your-base-url \
lego --dns excedo -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    EXCEDO_API_KEY = "API key"
    EXCEDO_API_URL = "API base URL"
  [Configuration.Additional]
    EXCEDO_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 10)"
    EXCEDO_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 300)"
    EXCEDO_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)"
    EXCEDO_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "none"
