Name = "Openprovider"
Description = ''''''
URL = "https://www.openprovider.com/"
Code = "openprovider"
Since = "v5.3.0"

Additional = '''
{{% notice style="warning" %}}

The provider is only available for resellers because the Openprovider API is only available for resellers.

{{% /notice %}}
'''

Example = '''
OPENPROVIDER_USERNAME="xxx" \
OPENPROVIDER_PASSWORD="yyy" \
lego run --dns openprovider -d '*.example.com' -d example.com
'''

[Configuration]
  [Configuration.Credentials]
    OPENPROVIDER_USERNAME = "The user's name"
    OPENPROVIDER_PASSWORD = "The user's password"
  [Configuration.Additional]
    OPENPROVIDER_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 10)"
    OPENPROVIDER_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 600)"
    OPENPROVIDER_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)"
    OPENPROVIDER_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://docs.openprovider.com/doc/all"
