package storage

import (
	"crypto"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"log/slog"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-acme/lego/v5/certcrypto"
	"github.com/go-acme/lego/v5/log"
)

const RootPathWarningMessage = `!!!! HEADS UP !!!!

Your account credentials have been saved in your
configuration directory at "%s".

You should make a secure backup of this folder now. This
configuration directory will also contain private keys
generated by lego and certificates obtained from the ACME
server. Making regular backups of this folder is ideal.
`

const (
	baseAccountsRootFolderName = "accounts"
	accountFileName            = "account.json"
)

type PrivateKeyNotFound struct {
	AccountID string
}

func (e *PrivateKeyNotFound) Error() string {
	return fmt.Sprintf("no private key found for account %q", e.AccountID)
}

type AccountsStorageConfig struct {
	BasePath string

	Server string
}

// AccountsStorage A storage for account data.
//
// rootPath:
//
//	./.lego/accounts/
//	     │      └── root accounts directory
//	     └── "path" option
//
// rootUserPath:
//
//	./.lego/accounts/localhost_14000/foo@example.com/
//	     │      │             │             └── accountID
//	     │      │             └── CA server ("server" option)
//	     │      └── root accounts directory
//	     └── "path" option
//
// keysPath:
//
//	./.lego/accounts/localhost_14000/foo@example.com/RSA4096/
//	     │      │             │             │          └── per key type directory
//	     │      │             │             └── accountID
//	     │      │             └── CA server ("server" option)
//	     │      └── root accounts directory
//	     └── "path" option
//
// accountFilePath:
//
//	./.lego/accounts/localhost_14000/foo@example.com/RSA4096/account.json
//	     │      │             │             │          │       └── account file
//	     │      │             │             │          └── per key type directory
//	     │      │             │             └── accountID
//	     │      │             └── CA server ("server" option)
//	     │      └── root accounts directory
//	     └── "path" option
type AccountsStorage struct {
	rootPath string

	server *url.URL
}

// NewAccountsStorage Creates a new AccountsStorage.
func NewAccountsStorage(config AccountsStorageConfig) (*AccountsStorage, error) {
	serverURL, err := url.Parse(config.Server)
	if err != nil {
		return nil, fmt.Errorf("invalid server URL %q: %w", config.Server, err)
	}

	return &AccountsStorage{
		rootPath: filepath.Join(config.BasePath, baseAccountsRootFolderName),
		server:   serverURL,
	}, nil
}

// GetRootPath returns the root path of the storage of the accounts.
func (s *AccountsStorage) GetRootPath() string {
	return s.rootPath
}

// Save saves the account to a file (only the JSON file).
func (s *AccountsStorage) Save(account *Account) error {
	if account.ID == "" {
		account.ID = account.GetID()
	}

	jsonBytes, err := json.MarshalIndent(account, "", "\t")
	if err != nil {
		return err
	}

	return os.WriteFile(s.getAccountFilePath(account.GetKeyType(), account.GetID()), jsonBytes, filePerm)
}

// Get gets an account from a file or creates a new one (the files are saved).
func (s *AccountsStorage) Get(keyType certcrypto.KeyType, email, accountID string) (*Account, error) {
	effectiveAccountID := getEffectiveAccountID(email, accountID)

	if !s.existsAccountFile(keyType, effectiveAccountID) {
		account, err := s.createAccount(keyType, email, accountID)
		if err != nil {
			return nil, err
		}

		err = s.Save(account)
		if err != nil {
			return nil, err
		}

		return account, nil
	}

	return s.getAccount(keyType, effectiveAccountID)
}

// createAccount creates a new account.
func (s *AccountsStorage) createAccount(keyType certcrypto.KeyType, email, accountID string) (*Account, error) {
	effectiveAccountID := getEffectiveAccountID(email, accountID)

	privateKey, err := s.createPrivateKey(keyType, effectiveAccountID)
	if err != nil {
		return nil, err
	}

	return &Account{
		ID:      effectiveAccountID,
		Email:   email,
		KeyType: keyType,
		key:     privateKey,
	}, nil
}

// getAccount gets the account from a file.
// It will flag the account as needing recovery if the registration is missing.
// And it will also create a new private key if it doesn't exist (and save the private key file).
func (s *AccountsStorage) getAccount(keyType certcrypto.KeyType, effectiveAccountID string) (*Account, error) {
	accountFilePath := s.getAccountFilePath(keyType, effectiveAccountID)

	fileBytes, err := os.ReadFile(accountFilePath)
	if err != nil {
		return nil, fmt.Errorf("could not read the account file %q: %w", accountFilePath, err)
	}

	account := new(Account)

	err = json.Unmarshal(fileBytes, account)
	if err != nil {
		return nil, fmt.Errorf("could not parse the account file %s: %w", accountFilePath, err)
	}

	account.key, err = s.readPrivateKey(keyType, effectiveAccountID)
	if err != nil {
		var privateKeyNotFound *PrivateKeyNotFound

		if !errors.As(err, &privateKeyNotFound) {
			return nil, err
		}

		// TODO(ldez): debug level?
		log.Info("No key found for the account. Generating a new private key.",
			slog.String("accountID", effectiveAccountID),
			slog.Any("keyType", keyType),
		)

		// The private key was regenerated, so the registration is no longer valid.
		account.Registration = nil

		account.key, err = s.createPrivateKey(keyType, effectiveAccountID)
		if err != nil {
			return nil, fmt.Errorf("new private key creation: %w", err)
		}

		err := s.Save(account)
		if err != nil {
			return nil, fmt.Errorf("could not save the account file: %w", err)
		}

		return account, nil
	}

	if account.Registration != nil && account.Registration.Status != "" {
		return account, nil
	}

	// The registration is missing, but there is an existing private key, so the account needs recovery.
	account.NeedsRecovery = true

	return account, nil
}

// createPrivateKey generates a new private key and saves it to a file.
func (s *AccountsStorage) createPrivateKey(keyType certcrypto.KeyType, effectiveAccountID string) (crypto.Signer, error) {
	accKeyPath := s.getAccountKeyPath(keyType, effectiveAccountID)
	keysPath := filepath.Dir(accKeyPath)

	err := CreateNonExistingFolder(keysPath)
	if err != nil {
		return nil, fmt.Errorf("could not check/create the directory %q for the account (accountID: %s): %w", keysPath, effectiveAccountID, err)
	}

	privateKey, err := certcrypto.GeneratePrivateKey(keyType)
	if err != nil {
		return nil, fmt.Errorf("private key generation (accountID: %s): %w", effectiveAccountID, err)
	}

	certOut, err := os.Create(accKeyPath)
	if err != nil {
		return nil, fmt.Errorf("private key file creation: (accountID: %s): %w", effectiveAccountID, err)
	}

	defer func() {
		_ = certOut.Close()

		// TODO(ldez): debug level?
		log.Info("Private key saved.", slog.String("filepath", accKeyPath))
	}()

	pemKey := certcrypto.PEMBlock(privateKey)

	err = pem.Encode(certOut, pemKey)
	if err != nil {
		return nil, fmt.Errorf("private key PEM encoding: (accountID: %s): %w", effectiveAccountID, err)
	}

	return privateKey, nil
}

// readPrivateKey reads the private key from a file.
func (s *AccountsStorage) readPrivateKey(keyType certcrypto.KeyType, effectiveAccountID string) (crypto.Signer, error) {
	accKeyPath := s.getAccountKeyPath(keyType, effectiveAccountID)

	if _, err := os.Stat(accKeyPath); os.IsNotExist(err) {
		return nil, &PrivateKeyNotFound{AccountID: effectiveAccountID}
	} else if err != nil {
		return nil, err
	}

	privateKey, err := ReadPrivateKeyFile(accKeyPath)
	if err != nil {
		return nil, fmt.Errorf("error loading the private key file %q: %w", accKeyPath, err)
	}

	return privateKey, nil
}

// existsAccountFile checks if the account file exists.
func (s *AccountsStorage) existsAccountFile(keyType certcrypto.KeyType, effectiveAccountID string) bool {
	accountFilePath := s.getAccountFilePath(keyType, effectiveAccountID)

	if _, err := os.Stat(accountFilePath); os.IsNotExist(err) {
		return false
	} else if err != nil {
		log.Fatal("Could not read the account file.",
			slog.String("filepath", accountFilePath),
			log.ErrorAttr(err),
		)
	}

	return true
}

func (s *AccountsStorage) getAccountKeyPath(keyType certcrypto.KeyType, effectiveAccountID string) string {
	return filepath.Join(s.getKeyPath(keyType, effectiveAccountID), effectiveAccountID+".key")
}

// getAccountFilePath returns the account file path.
func (s *AccountsStorage) getAccountFilePath(keyType certcrypto.KeyType, effectiveAccountID string) string {
	return filepath.Join(s.getKeyPath(keyType, effectiveAccountID), accountFileName)
}

// getKeyPath returns the path to the folder that contains the private key for an account.
func (s *AccountsStorage) getKeyPath(keyType certcrypto.KeyType, effectiveAccountID string) string {
	return filepath.Join(s.getRootUserPath(effectiveAccountID), string(keyType))
}

// getRootUserPath returns the path to the root folder for an account.
func (s *AccountsStorage) getRootUserPath(effectiveAccountID string) string {
	return filepath.Join(s.rootPath, sanitizeHost(s.server), effectiveAccountID)
}

func sanitizeHost(uri *url.URL) string {
	return strings.NewReplacer(":", "_", "/", string(os.PathSeparator)).Replace(uri.Host)
}
