Name = "omg.lol"
Description = ''''''
URL = "https://home.omg.lol/"
Code = "omglol"
Since = "v5.0.0"

Example = '''
OMGLOL_API_KEY="xx" \
lego run --dns omglol -d '*.example.com' -d example.com
'''

[Configuration]
  [Configuration.Credentials]
    OMGLOL_API_KEY = "API key"
  [Configuration.Additional]
    OMGLOL_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    OMGLOL_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    OMGLOL_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    OMGLOL_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://api.omg.lol/#dns"
