Name = "Xinnet"
Description = ''''''
URL = "https://www.xinnet.com/"
Code = "xinnet"
Since = "v5.0.0"

Example = '''
XINNET_SECRET="xxx" \
XINNET_AGENT_ID="agent12345" \
lego run --dns xinnet -d '*.example.com' -d example.com
'''

[Configuration]
  [Configuration.Credentials]
    XINNET_SECRET = "Application secret"
    XINNET_AGENT_ID = "Agent ID"
  [Configuration.Additional]
    XINNET_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    XINNET_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    XINNET_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    XINNET_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://apidoc.xin.cn/"
