Name = "Zilore"
Description = ''''''
URL = "https://zilore.com/en"
Code = "zilore"
Since = "v5.0.0"

Example = '''
ZILORE_ACCESS_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego run --dns zilore -d '*.example.com' -d example.com
'''

[Configuration]
  [Configuration.Credentials]
    ZILORE_ACCESS_KEY = "Access key"
  [Configuration.Additional]
    ZILORE_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    ZILORE_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    ZILORE_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    ZILORE_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://zilore.com/en/help/api"
