package main

const senderBaseUserAgent = "xenolf-acme/"

const senderSourceFile = "./acme/api/internal/sender/useragent.go"

const senderTemplate = `package sender

// Code generated by 'internal/useragent'; DO NOT EDIT.

const (
	// ourUserAgent is the User-Agent of this underlying library package.
	ourUserAgent = "xenolf-acme/{{ .version }}"

	// ourUserAgentComment is part of the UA comment linked to the version status of this underlying library package.
	// values: detach|release
	// NOTE: Update this with each tagged release.
	ourUserAgentComment = "{{ .comment }}"
)

`
