Name = "EuroDNS"
Description = ''''''
URL = "https://www.eurodns.com/"
Code = "eurodns"
Since = "v4.33.0"

Example = '''
EURODNS_APP_ID="xxx" \
EURODNS_API_KEY="yyy" \
lego --dns eurodns -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    EURODNS_APP_ID = "Application ID"
    EURODNS_API_KEY = "API key"
  [Configuration.Additional]
    EURODNS_POLLING_INTERVAL = "Time between DNS propagation check"
    EURODNS_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    EURODNS_TTL = "The TTL of the TXT record used for the DNS challenge"
    EURODNS_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://docapi.eurodns.com/"
