Name = "EuroDNS"
Description = ''''''
URL = "https://www.eurodns.com/"
Code = "eurodns"
Since = "v4.33.0"

Example = '''
EURODNS_APP_ID="xxx" \
EURODNS_API_KEY="yyy" \
lego --dns eurodns -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    EURODNS_APP_ID = "Application ID"
    EURODNS_API_KEY = "API key"
  [Configuration.Additional]
    EURODNS_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    EURODNS_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    EURODNS_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)"
    EURODNS_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://docapi.eurodns.com/"
